In [18]:
import pandas as pd
file_path = "../data/processed/clean_book_summaries.csv"
df = pd.read_csv(file_path)
df.sample(5)

,Title,Author,Genres,Summary
12632,Dreams of the Raven,NaN,['Science Fiction'],A mysterious distress call leads to the USS E...
1598,Distress,Greg Egan,"['Science Fiction', 'Speculative fiction', 'Fa...",It describes the political intrigue surroundi...
10002,Dead Right,Peter Robinson,"['Crime Fiction', 'Mystery']","On a rainy night in Eastvale, a teenager is f..."
1415,The Nutmeg of Consolation,Patrick O'Brian,"['Historical fiction', 'Fiction', 'Historical ...",The Nutmeg of Consolation opens with Aubrey a...
11376,A Mercy,Toni Morrison,['Novel'],"Florens, a slave, lives and works on Jacob Va..."

In [19]:
for col in ["Tone", "Pacing", "Aesthetic", "Themes"]:
    if col not in df.columns:
        df[col] = None

In [20]:
df.head()

,Title,Author,Genres,Summary,Tone,Pacing,Aesthetic,Themes
0,Animal Farm,George Orwell,"['Roman à clef', 'Satire', ""Children's literat...","Old Major, the old boar on the Manor Farm, ca...",None,None,None,None
1,A Clockwork Orange,Anthony Burgess,"['Science Fiction', 'Novella', 'Speculative fi...","Alex, a teenager living in near-future Englan...",None,None,None,None
2,The Plague,Albert Camus,"['Existentialism', 'Fiction', 'Absurdist ficti...",The text of The Plague is divided into five p...,None,None,None,None
3,An Enquiry Concerning Human Understanding,David Hume,['Uncategorized'],The argument of the Enquiry proceeds by a ser...,None,None,None,None
4,A Fire Upon the Deep,Vernor Vinge,"['Hard science fiction', 'Science Fiction', 'S...",The novel posits that space around the Milky ...,None,None,None,None

In [21]:
import os
from dotenv import load_dotenv
from groq import Groq
load_dotenv("../../.env")

True

In [22]:
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

In [34]:
promptCh = """You are a STRICT semantic classification engine.

Your task is to classify a book using ONLY the predefined labels below.

You will receive:
- Title (supporting signal)
- Existing genres (noisy hints, optional)
- Book summary (PRIMARY source of truth)

CLASSIFICATION RULES:

1) The BOOK SUMMARY is the primary source. The title may help to get faster meaning.
2) Existing genres are only hints and may be inaccurate.
3) Select labels ONLY from the allowed lists.
4) NEVER invent new labels, synonyms, or variations.
5) Labels must match EXACT spelling including underscores.
6) Be conservative. Assign labels ONLY when clearly dominant.
7) Prefer fewer strong labels over many weak ones.
8) If unsure between assigning a label or none, choose none.

Avoid assigning broad philosophical themes (identity, morality, existentialism)
unless explicitly central to the narrative.

OUTPUT FORMAT (STRICT):

Tone: label1,label2 OR none
Pacing: label1,label2 OR none
Aesthetic: label1,label2 OR none
Themes: label1,label2,label3 OR none

Formatting rules:
- No extra text.
- No explanations.
- No analysis.
- Use lowercase exactly as defined.
- Separate multiple labels using commas with NO spaces.

Allowed Tone Labels:
dark, melancholic, hopeful, tragic, uplifting, introspective, tense, humorous, romantic, mysterious, epic, whimsical

Allowed Pacing Labels:
slow_burn, fast_paced, character_driven, plot_driven, episodic

Allowed Aesthetic Labels:
dark_academia, cyberpunk, gothic, philosophical, cozy, surreal, dystopian, mythological, historical, high_fantasy, urban_fantasy, literary, science_fiction

Allowed Theme Labels:
coming_of_age, revenge, redemption, war, politics, technology, family, survival, love, loss, identity, existentialism, morality
INPUT:

Title:
{title}

Existing Genres (may be noisy):
{genres}

Book Summary:
{summary}
"""

In [24]:
import re
def parse_labels(llm_output):
    #Initalize empty dictionary
    data = {"Tone": "", "Pacing": "", "Aesthetic": "", "Themes": ""}
    patterns = {
        "Tone": r"Tone:\s*(.*)",
        "Pacing": r"Pacing:\s*(.*)",
        "Aesthetic": r"Aesthetic:\s*(.*)",
        "Themes": r"Themes:\s*(.*)"
    }
    for key, pattern in patterns.items():
        match = re.search(pattern, llm_output)
        if match:
            data[key] = match.group(1).strip()
    return data

In [26]:
import time
test_chunk = df.sample(n=200, random_state=42)
count = 1
for index, row in test_chunk.iterrows():
    start_time = time.time()

    user_input = f"""
Title:
{row['Title']}

Existing Genres (may be noisy):
{row['Genres']}

Book Summary:
{row['Summary']}
"""

    chat_completion = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        temperature=0.3,
        messages=[
            {"role": "system", "content": promptCh},
            {"role": "user", "content": user_input}
        ]
    )

    llm_output = chat_completion.choices[0].message.content

    parsed_data = parse_labels(llm_output)

    for category, labels in parsed_data.items():
        test_chunk.at[index, category] = labels

    print(f"[{count}/200] Index: {index} Classified: {row['Title']}")
    count += 1
    elapsed = time.time()
    if(elapsed < 3):
        time.sleep(3-elapsed)

[1/200] Index: 3169 Classified: The Boy Who Lost His Face
[2/200] Index: 4257 Classified: Tunnels of Blood
[3/200] Index: 4130 Classified: The Franchise
[4/200] Index: 2715 Classified: The Lady in the Lake
[5/200] Index: 10284 Classified: Skinnybones
[6/200] Index: 6292 Classified: The Family Trade
[7/200] Index: 11941 Classified: The Sand Dwellers
[8/200] Index: 2301 Classified: The Clerk's Prologue and Tale
[9/200] Index: 2718 Classified: The House of the Scorpion
[10/200] Index: 12297 Classified: The 3 Mistakes of My Life
[11/200] Index: 4104 Classified: Flyte
[12/200] Index: 9300 Classified: No Dominion
[13/200] Index: 6760 Classified: Haunted
[14/200] Index: 6345 Classified: Ordinary Jack
[15/200] Index: 16059 Classified: Melmoth
[16/200] Index: 5561 Classified: The Tale of Mr. Jeremy Fisher
[17/200] Index: 2271 Classified: Dream Story
[18/200] Index: 8937 Classified: The Measure of a Man: A Spiritual Autobiography
[19/200] Index: 426 Classified: War and Peace
[20/200] Index: 3325 Classified: The Nature of Alexander
[21/200] Index: 15523 Classified: The Color of Crime
[22/200] Index: 13074 Classified: The Clay Marble
[23/200] Index: 12143 Classified: The Iron Star
[24/200] Index: 6624 Classified: The Blue Equinox
[25/200] Index: 9728 Classified: Michael Tolliver Lives
[26/200] Index: 11588 Classified: Dreams of Trespass: Tales of a Harem Girlhood
[27/200] Index: 4993 Classified: This Other Eden
[28/200] Index: 12574 Classified: Gears of War: Aspho Fields
[29/200] Index: 14871 Classified: Little Bird of Heaven
[30/200] Index: 2325 Classified: The Man from Barbarossa
[31/200] Index: 1456 Classified: A Separate Peace
[32/200] Index: 13520 Classified: King of the Trollhaunt Warrens
[33/200] Index: 1659 Classified: The Old Curiosity Shop
[34/200] Index: 5998 Classified: Flying Colours
[35/200] Index: 16421 Classified: Destiny Times Three
[36/200] Index: 3341 Classified: Dragon and Phoenix
[37/200] Index: 2435 Classified: Backwards
[38/200] Index: 7356 Classified: Strange Meeting
[39/200] Index: 6306 Classified: The Keys to the Street
[40/200] Index: 3826 Classified: The Time of the Ghost
[41/200] Index: 14106 Classified: Ninth Grade Slays
[42/200] Index: 7796 Classified: Myrren's Gift
[43/200] Index: 6497 Classified: Peveril of the Peak
[44/200] Index: 2742 Classified: In Search of the Unknown
[45/200] Index: 387 Classified: Science and Health with Key to the Scriptures
[46/200] Index: 8289 Classified: Imperium
[47/200] Index: 12467 Classified: Feast of Souls
[48/200] Index: 1650 Classified: The Mysterious Island
[49/200] Index: 10476 Classified: The Emperor's Children
[50/200] Index: 10969 Classified: Brotherhood of the Rose
[51/200] Index: 2579 Classified: The Castle of Iron
[52/200] Index: 9344 Classified: Three Witnesses
[53/200] Index: 5532 Classified: Acorna's People
[54/200] Index: 13243 Classified: Blackthorn Winter
[55/200] Index: 12545 Classified: Designing Economic Mechanisms
[56/200] Index: 4794 Classified: How I Survived My Summer Vacation
[57/200] Index: 8649 Classified: Dragons in the Waters
[58/200] Index: 12295 Classified: Nerve
[59/200] Index: 5572 Classified: The Tailor of Gloucester
[60/200] Index: 8046 Classified: None But Lucifer
[61/200] Index: 11075 Classified: The Door in the Dragon's Throat
[62/200] Index: 10508 Classified: Trek to Madworld
[63/200] Index: 10949 Classified: Paloma
[64/200] Index: 7132 Classified: Staying Fat For Sarah Byrnes
[65/200] Index: 4519 Classified: A Strange Manuscript Found in a Copper Cylinder
[66/200] Index: 11848 Classified: Replay
[67/200] Index: 15852 Classified: We're Back! A Dinosaur's Story
[68/200] Index: 3 Classified: An Enquiry Concerning Human Understanding
[69/200] Index: 11415 Classified: 2nd Chance
[70/200] Index: 3964 Classified: Weapons of Choice
[71/200] Index: 10446 Classified: Bows Against the Barons
[72/200] Index: 1557 Classified: Lirael
[73/200] Index: 2791 Classified: Flambards Divided
[74/200] Index: 9781 Classified: Est: The Steersman Handbook
[75/200] Index: 7724 Classified: Deep River
[76/200] Index: 11510 Classified: Hotel for Dogs
[77/200] Index: 2450 Classified: In Enemy Hands
[78/200] Index: 1566 Classified: Leaven of Malice
[79/200] Index: 12122 Classified: The Radio Man
[80/200] Index: 5766 Classified: Path to Truth
[81/200] Index: 14251 Classified: Lowell Park
[82/200] Index: 47 Classified: Johnny Got His Gun
[83/200] Index: 8147 Classified: Thirteen Moons
[84/200] Index: 15705 Classified: Luv Ya Bunches
[85/200] Index: 4807 Classified: Visitors
[86/200] Index: 10214 Classified: Star Wars: Darth Bane: Rule of Two
[87/200] Index: 16118 Classified: Move Under Ground
[88/200] Index: 8332 Classified: Digging to America
[89/200] Index: 16183 Classified: Always Hiding
[90/200] Index: 3578 Classified: Island of the Lizard King
[91/200] Index: 13123 Classified: The Wicked Witch of Oz
[92/200] Index: 14327 Classified: Freedom
[93/200] Index: 15136 Classified: Deogratias
[94/200] Index: 7652 Classified: Breakfast at Tiffany's
[95/200] Index: 4294 Classified: A Question of Upbringing
[96/200] Index: 1166 Classified: At the Mountains of Madness
[97/200] Index: 9272 Classified: I Am the Messenger
[98/200] Index: 196 Classified: The Crow Road
[99/200] Index: 16211 Classified: Sementes no Gelo
[100/200] Index: 346 Classified: Becket
[101/200] Index: 11496 Classified: The President
[102/200] Index: 12965 Classified: The Sound of One Hand Clapping
[103/200] Index: 1056 Classified: Fortress Besieged
[104/200] Index: 19 Classified: Book of Haggai
[105/200] Index: 13141 Classified: Harriet's Halloween Candy
[106/200] Index: 15012 Classified: Giant Dinosaurs of the Jurassic
[107/200] Index: 6081 Classified: The Hunger of Sejanoz
[108/200] Index: 13976 Classified: The Lost Fleet: Relentless
[109/200] Index: 9402 Classified: And Kill Once More
[110/200] Index: 7496 Classified: Destiny: Child of the Sky
[111/200] Index: 8223 Classified: The Courts of the Morning
[112/200] Index: 5858 Classified: The Captain
[113/200] Index: 8816 Classified: In Times Like These
[114/200] Index: 11032 Classified: Djinn
[115/200] Index: 6311 Classified: The Crocodile Bird
[116/200] Index: 15115 Classified: The Twelfth Card
[117/200] Index: 7744 Classified: Daja's Book
[118/200] Index: 327 Classified: The Sandman: Dream Country
[119/200] Index: 1034 Classified: The Mayor of Casterbridge: The Life and Death of a Man of Character
[120/200] Index: 8071 Classified: Sharpe's Christmas
[121/200] Index: 11923 Classified: Keeper of the Doves
[122/200] Index: 5157 Classified: Nemesis
[123/200] Index: 15903 Classified: Shards of a Broken Crown
[124/200] Index: 9811 Classified: The Golden Rendezvous
[125/200] Index: 1624 Classified: Day of Al'Akbar
[126/200] Index: 8612 Classified: Damia's Children
[127/200] Index: 16174 Classified: Busabos ng Palad
[128/200] Index: 6822 Classified: Gil's All Fright Diner
[129/200] Index: 409 Classified: Master and Commander
[130/200] Index: 7834 Classified: Mark Coffin U.S.S.
[131/200] Index: 2584 Classified: Anne of the Island
[132/200] Index: 7765 Classified: Salt
[133/200] Index: 3090 Classified: The True Story of Ah Q
[134/200] Index: 3482 Classified: The Matchlock Gun
[135/200] Index: 12382 Classified: Starting With Alice
[136/200] Index: 4688 Classified: Love Among the Chickens
[137/200] Index: 8957 Classified: A Escrava Isaura
[138/200] Index: 8731 Classified: Caesar
[139/200] Index: 9934 Classified: The Judas Window
[140/200] Index: 5719 Classified: Dragons of Spring Dawning
[141/200] Index: 8990 Classified: The Case of Miss Elliot
[142/200] Index: 123 Classified: The Grapes of Wrath
[143/200] Index: 6005 Classified: By the Light of the Moon
[144/200] Index: 13561 Classified: Da Tang You Xia Zhuan
[145/200] Index: 14342 Classified: A Dubious Legacy
[146/200] Index: 2140 Classified: The Stupidest Angel
[147/200] Index: 5992 Classified: Second Chance
[148/200] Index: 2232 Classified: Edward II
[149/200] Index: 13104 Classified: The Rise and Fall of Freedom of Contract
[150/200] Index: 5701 Classified: The House of the Seven Gables
[151/200] Index: 8406 Classified: Thunder Cave
[152/200] Index: 11864 Classified: Operation: Outer Space
[153/200] Index: 14751 Classified: All in the Mind
[154/200] Index: 8985 Classified: Keeper
[155/200] Index: 14335 Classified: The Cater Street Hangman
[156/200] Index: 9443 Classified: Under the Mat: Inside Wrestling's Greatest Family
[157/200] Index: 4455 Classified: All the Weyrs of Pern
[158/200] Index: 8878 Classified: The Amazon Temple Quest
[159/200] Index: 8051 Classified: Death du Jour
[160/200] Index: 8496 Classified: Lord Tony's Wife
[161/200] Index: 291 Classified: Picnic at Hanging Rock
[162/200] Index: 14815 Classified: Volga Se Ganga
[163/200] Index: 10774 Classified: The Blacker the Berry
[164/200] Index: 16048 Classified: Ash: A Secret History
[165/200] Index: 15425 Classified: The Silver Ship and the Sea
[166/200] Index: 13237 Classified: A Heart So White
[167/200] Index: 11337 Classified: To Wake the Dead
[168/200] Index: 4230 Classified: Kamikaze Girls
[169/200] Index: 16274 Classified: Machine Man
[170/200] Index: 4720 Classified: Balthasar's Odyssey
[171/200] Index: 3721 Classified: The Ticket That Exploded
[172/200] Index: 8786 Classified: Le Colonel Chabert
[173/200] Index: 4852 Classified: So You Want to Be a Wizard
[174/200] Index: 7775 Classified: Gradisil
[175/200] Index: 14907 Classified: The Mostly True Adventures of Homer P. Figg
[176/200] Index: 5847 Classified: The Stone Carvers
[177/200] Index: 3615 Classified: The Real Eve
[178/200] Index: 7181 Classified: A Conspiracy of Paper: A Novel
[179/200] Index: 8166 Classified: The Cobra Event
[180/200] Index: 1767 Classified: Island of the Blue Dolphins
[181/200] Index: 1393 Classified: Fallen Angels
[182/200] Index: 5681 Classified: Icon
[183/200] Index: 8916 Classified: Tarzan the Terrible
[184/200] Index: 7711 Classified: High Deryni
[185/200] Index: 12136 Classified: The Widows of Eastwick
[186/200] Index: 10884 Classified: Solip:System
[187/200] Index: 2458 Classified: Collapse: How Societies Choose to Fail or Succeed
[188/200] Index: 12901 Classified: Wooden Leg: A Warrior Who Fought Custer
[189/200] Index: 657 Classified: Sign of the Unicorn
[190/200] Index: 12887 Classified: Thunderspire Labyrinth
[191/200] Index: 16373 Classified: After the Fire, A Still Small Voice
[192/200] Index: 15259 Classified: The Interpreter
[193/200] Index: 16177 Classified: Roshan and Ashmi
[194/200] Index: 14376 Classified: Impossible
[195/200] Index: 10401 Classified: Sam and the Firefly
[196/200] Index: 10292 Classified: Seeing
[197/200] Index: 6492 Classified: Fleshmarket Close
[198/200] Index: 7816 Classified: Eucalyptus
[199/200] Index: 16247 Classified: Torn
[200/200] Index: 9801 Classified: The Troublesome Offspring of Cardinal Guzman

In [35]:
test_chunk.sample(20)

,Title,Author,Genres,Summary,Tone,Pacing,Aesthetic,Themes
6822,Gil's All Fright Diner,A. Lee Martinez,"['Science Fiction', 'Speculative fiction']","In the backwoods southern town of Rockwood, a...",humorous,fast_paced,none,none
3,An Enquiry Concerning Human Understanding,David Hume,['Uncategorized'],The argument of the Enquiry proceeds by a ser...,"introspective, melancholic",slow_burn,philosophical,"existentialism, identity, morality, power_corr..."
8990,The Case of Miss Elliot,Baroness Emma Orczy,['Uncategorized'],"Despite his vanity about his own talents, Bil...",humorous,character_driven,none,"identity, morality"
8147,Thirteen Moons,Charles Frazier,['Historical novel'],"Near the end of his life, frontiersman Will C...","melancholic,tragic",slow_burn,historical,"identity,loss,power_corruption,love,survival"
16059,Melmoth,NaN,['Uncategorized'],"After Jaka, Rick and Oscar's arrest (and Pud'...",,,,
4794,How I Survived My Summer Vacation,NaN,['Horror'],:Written by Michelle Sagara West Buffy contin...,"hopeful, melancholic",fast_paced,none,"identity, loss, redemption"
13123,The Wicked Witch of Oz,Rachel Cosgrove Payes,['Fantasy'],"The title character is Singra, the Wicked Wit...","hopeful, tragic",fast_paced,none,"redemption, morality"
11415,2nd Chance,James Patterson,"['Crime Fiction', 'Mystery', 'Fiction', 'Suspe...",Homicide Lieutenant Lindsay Boxer is still re...,"tragic, hopeful",fast_paced,none,"revenge, identity"
5701,The House of the Seven Gables,Nathaniel Hawthorne,"['Horror', 'Mystery', 'American Gothic Fiction...","The novel is set in the mid-19th century, wit...","melancholic,tragic",character_driven,gothic,"identity, power_corruption, redemption, loss"
10949,Paloma,Kristine Kathryn Rusch,"['Science Fiction', 'Speculative fiction', 'De...","Miles Flint, a retrieval artist, returns to t...",,,,
5561,The Tale of Mr. Jeremy Fisher,Beatrix Potter,"[""Children's literature"", 'Fiction']",Jeremy Fisher is a frog who lives in a damp l...,humorous,slow_burn,none,none
7356,Strange Meeting,Susan Hill,['Uncategorized'],The novel begins with the protagonist of the ...,"tragic, melancholic, introspective",slow_burn,none,"identity, existentialism, power_corruption, mo..."
4257,Tunnels of Blood,Darren Shan,"['Young adult literature', ""Children's literat...","This story introduces Gavner Purl, a full vam...","hopeful, romantic",fast_paced,none,"identity, love, survival"
10774,The Blacker the Berry,Wallace Thurman,"['Historical fiction', 'Fiction']",";Part 1 Emma Lou Born in Boise, Idaho, Emma L...","melancholic, introspective",slow_burn,none,"identity, power_corruption, coming_of_age, los..."
6624,The Blue Equinox,Aleister Crowley,['Uncategorized'],"The Blue Equinox opens with Crowley's poem ""H...",none,none,none,none
16247,Torn,Amanda Hocking,['Paranormal romance'],The start of the book begins almost exactly w...,"hopeful, romantic",character_driven,none,"identity, love, family"
15259,The Interpreter,Suki Kim,['Novel'],"Suzy Park is a young, attractive, and achingl...","introspective, melancholic",character_driven,none,"identity, power_corruption, loss"
14376,Impossible,Danielle Steel,['Novel'],Sasha's husband suddenly dies leaving her wid...,"romantic, hopeful",none,none,"love, loss, identity"
3615,The Real Eve,Stephen Oppenheimer,"['Anthropology', 'Sociology']","In the book, Oppenheimer supports the theory ...",none,none,none,"identity, existentialism, power_corruption, mo..."
7765,Salt,Adam Roberts,"['Science Fiction', 'Speculative fiction']",Colonists from Earth set out for a distant pl...,"dark, tense",plot_driven,dystopian,"power_corruption, morality, war"

In [36]:
theme_series = (
    test_chunk['Themes']
    .dropna()
    .str.split(',')
    .explode()
    .str.strip()
)

print(theme_series.value_counts())

Themes
identity            137
power_corruption    101
morality             61
loss                 54
survival             44
redemption           42
love                 36
family               35
existentialism       23
                     22
coming_of_age        17
revenge              14
war                  12
none                 10
society              10
technology            7
politics              2
friendship            2
innocence             1
guilt                 1
judgement             1
apocalypse            1
Name: count, dtype: int64

In [37]:
test_chunk['meaning'] = (
    "Title: " + test_chunk['Title'].fillna('') +
    " Summary: " + test_chunk['Summary'].fillna('') +
    " Tone: " + test_chunk['Tone'].fillna('none') +
    " Pacing: " + test_chunk['Pacing'].fillna('none') +
    " Aesthetic: " + test_chunk['Aesthetic'].fillna('none') +
    " Themes: " + test_chunk['Themes'].fillna('none')
)

In [38]:
test_chunk.head()

,Title,Author,Genres,Summary,Tone,Pacing,Aesthetic,Themes,meaning
3169,The Boy Who Lost His Face,Louis Sachar,"[""Children's literature"", 'Young adult literat...","In a 1989 suburban town, a boy named David tr...","hopeful, introspective, humorous",character_driven,none,"identity, coming_of_age, redemption",Title: The Boy Who Lost His Face Summary: In ...
4257,Tunnels of Blood,Darren Shan,"['Young adult literature', ""Children's literat...","This story introduces Gavner Purl, a full vam...","hopeful, romantic",fast_paced,none,"identity, love, survival",Title: Tunnels of Blood Summary: This story i...
4130,The Franchise,Peter Gent,['Uncategorized'],Taylor Rusk is a star college quarterback and...,"dark,tragic",fast_paced,none,"power_corruption, identity, revenge",Title: The Franchise Summary: Taylor Rusk is ...
2715,The Lady in the Lake,Raymond Chandler,"['Crime Fiction', 'Detective fiction', 'Novel'...","Derace Kingsley, a wealthy businessman, hires...","dark, tragic",slow_burn,none,"power_corruption, revenge, identity, morality",Title: The Lady in the Lake Summary: Derace K...
10284,Skinnybones,Barbara Park,"[""Children's literature"", 'Fiction']",Alex wrote a letter in a promotional contest ...,"hopeful, humorous",fast_paced,none,"identity, coming_of_age",Title: Skinnybones Summary: Alex wrote a lett...

In [39]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")

/home/shivam/Projects/Books4U/server-model/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 586.41it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [40]:
print("Generating embeddings .....")
embeddings = model.encode(test_chunk['meaning'].to_list(), show_progress_bar=True)

print("Embeddings shape ", embeddings.shape)

Generating embeddings .....

Batches: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.64it/s]

Embeddings shape  (200, 384)

In [41]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
def search_books(query, top_n=5):
    query_vector = model.encode([query])
    similarities = cosine_similarity(query_vector, embeddings)[0]
    top_indices = np.argsort(similarities)[-top_n:][::-1]
    results = test_chunk.iloc[top_indices].copy()
    results['similarity_score'] = similarities[top_indices]
    
    return results[['Title', 'Author', 'Genres', 'similarity_score']]

In [42]:
search_books("dark academia")

,Title,Author,Genres,similarity_score
5157,Nemesis,Scott Ciencin,"['Speculative fiction', 'Horror']",0.404754
13243,Blackthorn Winter,Kathryn Reiss,"['Mystery', 'Young adult literature']",0.373075
16118,Move Under Ground,Nick Mamatas,"['Horror', 'Speculative fiction', 'Mystery', '...",0.335953
9300,No Dominion,Charlie Huston,"['Thriller', 'Horror', 'Speculative fiction', ...",0.328588
8046,None But Lucifer,H. L. Gold,"['Speculative fiction', 'Fantasy']",0.297866

In [43]:
search_books("character-driven philosophical sci-fi")

,Title,Author,Genres,similarity_score
16421,Destiny Times Three,Fritz Leiber,"['Science Fiction', 'Novel']",0.371650
9781,Est: The Steersman Handbook,Leslie Stevens,['Science Fiction'],0.354842
7765,Salt,Adam Roberts,"['Science Fiction', 'Speculative fiction']",0.343208
5157,Nemesis,Scott Ciencin,"['Speculative fiction', 'Horror']",0.339165
11864,Operation: Outer Space,Murray Leinster,"['Science Fiction', 'Speculative fiction']",0.333407

In [44]:
search_books("political dystopia.")

,Title,Author,Genres,similarity_score
16421,Destiny Times Three,Fritz Leiber,"['Science Fiction', 'Novel']",0.297160
4993,This Other Eden,Ben Elton,"['Speculative fiction', 'Fiction', 'Dystopia']",0.293488
7765,Salt,Adam Roberts,"['Science Fiction', 'Speculative fiction']",0.281931
9781,Est: The Steersman Handbook,Leslie Stevens,['Science Fiction'],0.259705
5681,Icon,Frederick Forsyth,"['Thriller', 'Novel']",0.253788

In [45]:
search_books("time loop story and philosophy")

,Title,Author,Genres,similarity_score
14251,Lowell Park,NaN,"['Historical fiction', 'Historical novel']",0.456626
16421,Destiny Times Three,Fritz Leiber,"['Science Fiction', 'Novel']",0.402985
291,Picnic at Hanging Rock,Joan Lindsay,"['Mystery', 'Historical novel']",0.369295
3826,The Time of the Ghost,Diana Wynne Jones,"['Ghost story', ""Children's literature"", 'Spec...",0.352429
8816,In Times Like These,Zee Edgell,"['History', 'Novel']",0.350784

In [46]:
search_books("moral dilemma involving artificial intelligence")

,Title,Author,Genres,similarity_score
4993,This Other Eden,Ben Elton,"['Speculative fiction', 'Fiction', 'Dystopia']",0.268198
9272,I Am the Messenger,Markus Zusak,['Fiction'],0.254824
2140,The Stupidest Angel,Christopher Moore,"['Speculative fiction', 'Horror', 'Comic fanta...",0.247489
8990,The Case of Miss Elliot,Baroness Emma Orczy,['Uncategorized'],0.227795
12545,Designing Economic Mechanisms,Leonid Hurwicz,['Uncategorized'],0.227704

In [47]:
search_books("lonely but beautiful")

,Title,Author,Genres,similarity_score
14376,Impossible,Danielle Steel,['Novel'],0.319853
15705,Luv Ya Bunches,Lauren Myracle,['Literary fiction'],0.306727
16174,Busabos ng Palad,NaN,['Novel'],0.278655
5532,Acorna's People,Elizabeth Ann Scarborough,"['Science Fiction', 'Speculative fiction', 'Fa...",0.260821
6081,The Hunger of Sejanoz,Joe Dever,"['Gamebook', ""Children's literature""]",0.256551